version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/logs:/app/logs
    env_file:
      - .env
    ports:
      - "8000:8000"
